name: build and test on requests.yml
#taken from the premade github workflows particularly the .NET workflow
#https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      # Set the environment variables from GitHub secrets
      auth_github_clientId: ${{ secrets.LOCALHOSTGITHUB_CLIENTID }}
      auth_github_clientSecret: ${{ secrets.LOCALHOSTGITHUB_SECRET }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: |
          npm install
          npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Build
        run: dotnet build --no-restore
      - name: Start server
        run: dotnet run --project src/Chirp.Razor/Chirp.Razor.csproj &
      - name: Wait for server to be ready
        run: sleep 10 # Adjust the sleep duration if needed
      - name: Test
        run: dotnet test --no-build --verbosity normal
