name: build and test on requests.yml
#taken from the premade github workflows particularly the .NET workflow
#https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
#this comment is here to let met make a pull request to test the functionality of this file
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
