# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - bdsagroup1chirpremotedb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.x'

      - name: Install Oryx
        run: |
          wget https://github.com/microsoft/Oryx/releases/download/20231027.1/oryx_linux_x64.tar.gz
          tar -xzf oryx_linux_x64.tar.gz
          sudo mv oryx /usr/local/bin/oryx

      - name: Build with dotnet
        run: dotnet build src/Chirp.CSVDBService/ --configuration Release

      - name: Build with Oryx
        run: oryx build src/Chirp.CSVDBService/ --platform dotnet --platform-version 7.0

      - name: dotnet publish
        run: dotnet publish src/Chirp.CSVDBService/ -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BC9EA1ADBA964FF9972433DDA000BCA0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DE53A73A0A404B468903D3AFA9A12B9B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B98A0E741D514664916F813CC9E2A1AD }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bdsagroup1chirpremotedb'
          slot-name: 'Production'
          package: .
          
