name: make release on tagged push
permissions: write-all

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+[a-zA-Z0-9]*"]
    branches: ["main"]

jobs:
    build_and_test:
        runs-on: ubuntu-latest
         
        steps:
          - run: |
             TAG_NAME=${GITHUB_REF#refs/tags/}
             echo "Tag name extracted from GITHUB_REF: $TAG_NAME"
             echo "Tag name from github.ref_name: ${{  steps.changelog.outputs.tag }}"
          - uses: actions/checkout@v4
          - name: Setup .NET
            uses: actions/setup-dotnet@v4
            with:
              dotnet-version: 7.0.x
          - name: Restore dependencies
            run: dotnet restore
          - name: Build
            run: dotnet build --no-restore
          - name: Test
            run: dotnet test --no-build --verbosity normal

    make_executables:
        needs: build_and_test
        runs-on: ubuntu-latest
        
        steps: 
          - name: Checkout
            uses: actions/checkout@v1

          - name: Setup dotnet
            uses: actions/setup-dotnet@v1
            with:
              dotnet-version: 3.1.101
            

