name: make release on tagged push
permissions: write-all

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]
    # branches: ["main"]


# Very much help from ChatGPT and Sif <esja@itu.dk>
jobs:
    build_and_test:
        runs-on: ubuntu-latest
         
        steps:
          - uses: actions/checkout@v4
          - name: Setup .NET
            uses: actions/setup-dotnet@v4
            with:
              dotnet-version: 7.0.x
          - name: Restore dependencies
            run: dotnet restore
          - name: Build
            run: dotnet build --no-restore
          #- name: Test
          #  run: dotnet test --no-build --verbosity normal

    make_executables:
        needs: build_and_test
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

#        strategy:
#          matrix:
#            os: [ubuntu-latest, macos-latest, windows-latest]
#            include:
#              - os: ubuntu-latest
#                rid: linux-x64
#              - os: macos-latest
#                rid: osx-x64
#              - os: windows-latest
#                rid: win-x64
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup .NET 8 SDK
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '8.x'
    
        - name: restoring projects
          run: | 
              dotnet restore 

        - name: building projects
          run: |
            dotnet build 

        - name: Publish standalone app for each platform
          run: |
            dotnet publish ./src/Chirp.CLI -c Release -r win-x64 --self-contained -o ./artifacts/win
            dotnet publish ./src/Chirp.CLI -c Release -r linux-x64 --self-contained -o ./artifacts/linux
            dotnet publish ./src/Chirp.CLI -c Release -r osx-x64 --self-contained -o ./artifacts/mac
          shell: bash

        - name: zips
          run: |
            zip -r Chirp-win.zip ./artifacts/win
            zip -r Chirp-linux.zip ./artifacts/linux
            zip -r Chirp-mac.zip ./artifacts/mac

        - name: Release
          uses: softprops/action-gh-release@v2
          with:
            name: release ${{ github.ref_name }}
            files: | 
                Chirp-win.zip
                Chirp-linux.zip
                Chirp-mac.zip