name: Move Assigned Issues to In Progress

on:
  issues:
    types: [assigned]

jobs:
  update_issue_status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      # Step 1: Retrieve the STATUS_FIELD_ID and IN_PROGRESS_OPTION_ID from the organization project
      - name: Fetch Status Field ID and In Progress Option ID
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          ORGANIZATION: ITU-BDSA2024-GROUP1
          PROJECT_NUMBER: 1
        run: |
          gh api graphql -f query='
            query($org: String!, $number: Int!) {
              organization(login: $org){
                projectV2(number: $number) {
                  id
                  fields(first:100) {
                    nodes {
                      ... on ProjectV2Field {
                        id
                        name
                      }
                      ... on ProjectV2SingleSelectField {
                        id
                        name
                        options {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            }' -f org=$ORGANIZATION -F number=$PROJECT_NUMBER > project_data.json

          echo 'PROJECT_ID='$(jq '.data.organization.projectV2.id' project_data.json) >> $GITHUB_ENV
          echo 'STATUS_FIELD_ID='$(jq '.data.organization.projectV2.fields.nodes[] | select(.name== "Status") | .id' project_data.json) >> $GITHUB_ENV
          echo 'IN_PROGRESS_OPTION_ID='$(jq '.data.organization.projectV2.fields.nodes[] | select(.name== "Status") | .options[] | select(.name=="In Progress") |.id' project_data.json) >> $GITHUB_ENV

          # echo "Issue IDs and Titles:"
          # cat project_data.json | jq -r '.data.organization.projectV2.items.nodes[] | "ID: \(.content.id), Title: \(.content.title)"


      # Step 2: Update the issue status to "In Progress"
      - name: Modify issue status to "In Progress"
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        run: |
          curl --request POST \
          --url https://api.github.com/graphql \
          --header 'Authorization: Bearer ${{ secrets.ACTIONS_TOKEN }}' \
          --data '{"query":"mutation {updateProjectV2ItemFieldValue( input: { projectId: \"'${{ env.PROJECT_ID }}'\" itemId: \"I_kwDOMpeEds6WL0U7\" fieldId: \"PVTSSF_lADOCrYi5c4AnZd9zgfI8tk\" value: { singleSelectOptionId: \"47fc9ee4\" }}) { projectV2Item { id }}}"}'


      - name: testing away
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          ORGANIZATION: ITU-BDSA2024-GROUP1
          PROJECT_NUMBER: 1
        run : |
          gh api graphql -f query='
            query { 
              organization(login: $org){
                projectV2(number: $number) {
                   edges {
                     node {
                        id 
                        title
                        url
                        number
                        state
                        author {
                          url
                        }
                        labels(first:5) {
                          edges {
                            node {
                              name
                            }
                          }
                        }
                      body
                    }
                  }
                }
              }
            }' -f org=$ORGANIZATION -F number=$PROJECT_NUMBER
