# Made by help of ChatGPT
name: Move Assigned Issues to In Progress

on:
  issues:
    types:
      - assigned

jobs:
  move-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Move issue to "In Progress"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node ./scripts/move-issue.js $GITHUB_TOKEN ${{ github.event.issue.node_id }} "In Progress"

      - name: Install Node.js (for the script)
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Run script
        run: node scripts/move-issue.js
