name: move assigned issues
on: 
  issues:
    types:
      - assigned
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@7ffb872c64bd809d23563a130a0a97d01dfa8f43
        with:
          project: YAML experiment
          column: In Progress
          repo-token: ${{ secrets.ACTIONS_TOKEN }}
