# Made by help of ChatGPT
name: Move Assigned Issues to In Progress

on:
  issues:
    types:
      - assigned

jobs:
  move-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # or 18 if you prefer to match your local environment

      - name: Install dependencies
        run: npm install @octokit/graphql

      - name: Move issue to "In Progress"
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        run: |
          node ./scripts/move-issue.js $GITHUB_TOKEN ${{ github.event.issue.node_id }} "In Progress"

